# Generated by Django 5.0.1 on 2024-08-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_contact_num_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_num',
            field=models.CharField(max_length=10),
        ),
    ]
